@api_HostAddress = http://localhost:3000
@productId = 2


### Get All products
GET {{api_HostAddress}}/Product
Accept: application/json

### Get one product
GET {{api_HostAddress}}/Product/{{{{productId}}}}
Accept: application/json
